apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-gke
  labels:
    app: odoo-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-gke
  template:
    metadata:
      labels:
        app: odoo-gke
    spec:
      containers:
      - name: odoo-gke
        image: odoo
        ports:
        - containerPort: 8069
        securityContext:
          privileged: true
          runAsUser: 0 
        env:
        - name: HOST
          #value: 35.198.22.242 ---- IP Publica Cloud SQL instancia Odoo17
          value: 10.68.48.28
        - name: USER
          value: odoo
        - name: PASSWORD
          value: Naipa1Xo-test
        - name: ODOO_PROTOCOL
          value: "https"
        - name: ODOO_PORT
          value: "443"
        #- name: addons_path
        #  value: /mnt/extra-addons
        volumeMounts:
        - name: pv-test-odoo-pm-01
          mountPath: /mnt/extra-addons
          subPath: extra-addons
        - name: pv-test-odoo-pm-02
          mountPath: /etc/odoo
          subPath: odoo
        - name: pv-test-odoo-pm-03
          mountPath: /root
          subPath: root
        - name: test-odoo-pm-config
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
      volumes:
      - name: pv-test-odoo-pm-01
        persistentVolumeClaim:
          claimName: pvc-test-odoo-proyectos-01
      - name: pv-test-odoo-pm-02
        persistentVolumeClaim:
          claimName: pvc-test-odoo-proyectos-02
      - name: pv-test-odoo-pm-03
        persistentVolumeClaim:
          claimName: pvc-test-odoo-proyectos-03
      - name: test-odoo-pm-config
        configMap:
          name: test-odoo-pm-config

---
# Dentro del ConfigMap tenemos que cargar todos los parametros del odoo.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-odoo-pm-config
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    logfile = /var/log/odoo/openerp-server.log
    log-level = error
    logrotate = False
    secure = True
    proxy_mode = True
