apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-odoo-proyectos
  labels:
    app: test-odoo-proyectos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-odoo-proyectos
  template:
    metadata:
      labels:
        app: test-odoo-proyectos
    spec:
      containers:
      - name: test-odoo-proyectos
        image: odoo
        ports:
        - containerPort: 8069
        securityContext:
          #allowPrivilegeEscalation: false
          privileged: true
          runAsUser: 0
          #runAsGroup: 3000
          #fsGroup: 2000
          #readOnlyRootFilesystem: false
        env:
        - name: HOST
          #value: 35.198.22.242 ---- IP Publica Cloud SQL instancia Odoo17
          value: 10.68.48.28
        - name: USER
          value: odoo
        - name: PASSWORD
          value: Naipa1Xo-test
        - name: ODOO_PROTOCOL
          value: "https"
        - name: ODOO_PORT
          value: "443"
        #- name: addons_path
        #  value: /mnt/extra-addons
        volumeMounts:
        - name: pv-test-odoo-pm-01
          mountPath: /mnt/extra-addons
          subPath: extra-addons
        - name: pv-test-odoo-pm-02
          mountPath: /etc/odoo
          subPath: odoo
        - name: pv-test-odoo-pm-03
          mountPath: /root
          subPath: root
        - name: test-odoo-pm-config
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
      volumes:
      - name: pv-test-odoo-pm-01
        persistentVolumeClaim:
          claimName: pvc-test-odoo-proyectos-01
      - name: pv-test-odoo-pm-02
        persistentVolumeClaim:
          claimName: pvc-test-odoo-proyectos-02
      - name: pv-test-odoo-pm-03
        persistentVolumeClaim:
          claimName: pvc-test-odoo-proyectos-03
      - name: test-odoo-pm-config
        configMap:
          name: test-odoo-pm-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-odoo-proyectos-01
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/pv-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-odoo-proyectos-01
  namespace: default
  labels:
    app: test-odoo-proyectos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-odoo-proyectos-02
  namespace: default
  labels:
    app: test-odoo-proyectos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-odoo-proyectos-03
  namespace: default
  labels:
    app: test-odoo-proyectos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
# Dentro del ConfigMap tenemos que cargar todos los parametros del odoo.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-odoo-pm-config
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    logfile = /var/log/odoo/openerp-server.log
    log-level = error
    logrotate = False
    secure = True
    proxy_mode = True
